config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :users
  get 'articles/search'
  get 'welcome/index'
  # get 'models/sign_in'
 root 'welcome#index'
  resources :articles do
  resources :comments
  #root to: 'home#index'
  end

 end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :timeoutable
        #  :lockable, :timeoutable, :trackable and :omniauthable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    accepts_nested_attributes_for :comments, reject_if: proc {|attributes| attributes['commenter'].blank?}
  # validates :title, presence: true, length: { minimum: 5 }
   
  def self.search(search)
    if search
        @article = Article.where('title LIKE ?', "%#{search}%")
    else
      @article = Article.all
    end
    end

end

app/models/comment.rb
class Comment < ApplicationRecord
 belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_admin!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    
    # http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
    def index
      # @articles = Article.all
      #@articles = Article.search(params[:search])
      @articles = Article.paginate(page: params[:page], per_page: 5).order("created_at DESC")
    end
   
    def show
      @article = Article.find(params[:id])
    end
    
    # def self.search 
    #   # @article = Article.where("title LIKE ? OR text LIKE ?", "%#{params[:search]}%")

    #   if params[:search].blank?  
    #     redirect_to(articles_path, alert: "Empty field!") and return  
    #   else  
    #     @parameter = params[:search] 
    #     @results = Article.all.where("lower(title) LIKE :search", search: @parameter)  
    #   end   
    # end
   
    def new
      @article = Article.new

    end
   
    def edit
      @article = Article.find(params[:id])
    end
   
    def create
      @article = Article.new(article_params)
   
      if @article.save
        redirect_to @article
      else
        render 'new'
      end
    end
   
    def update
      @article = Article.find(params[:id])
   
      if @article.update(article_params)
        redirect_to @article
      else
        render 'edit'
      end
    end
   
    def destroy
      @article = Article.find(params[:id])
      @article.destroy
      # redirect_to articles_path
      respond_to do |format|
        
        format.html { respond_to article_params, notice: 'Article was successfully remove '}
        format.json { head :no_content }
        format.js
      end
    end
   
    private
      def article_params
        params.require(:article).permit(:title, :text, :password)
      end
  end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
 
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_model!
  # user_signed_in?
  # current_user
  # user_session

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        # UserMailer.welcome_email(@user).deliver_now
        UserMailer.with(user: @user).welcome_email.deliver_later
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :login)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
   
 <div id="delete_<%= article.id%>">
 <div style="background:gray" class="my-3"><br>
 <div class="container">  
    <h6> <div> <b><%= article.title%></b><br>
      <%= article.text %>
      <%# <%= article.password %></div></h6>    
      
      <div><%= link_to 'Show', article_path(article) , :class => 'btn btn-success'%>
      <%= link_to 'Edit', edit_article_path(article) , :class => 'btn btn-info'%>
      <%= link_to 'Destroy', article_path(article),
              method: :delete,
              remote: true,
              data: { confirm: 'Are you sure?' }, class:"delete" , :class => 'btn btn-warning'%>
   </div> <br></div><br>
   </div>
   </div>

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
      
    </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
      <%= form.submit %>
<%= select_year(Time.new(2009)) %><% end %>

<%= form_with model: @article do |f| %>
  <%= f.file_field :picture %>
  
<% end %>
<%= form_with url: 'https://www.google.com/', authenticity_token: 'external_token' do %>
  Form contents
<% end %>

app/views/articles/destroy.js.erb
$('#delete_<%= @article.id %>').remove();  

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path, :class => 'btn btn-primary'%>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>
<%= link_to 'New article', new_article_path, :class => 'btn btn-primary'%>

<div>
  <%# <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="9"></th>
  </tr> %>
 
  <% @articles.each do |article| %>
   <%= render partial: 'article', locals:{article: article} %>
  <% end %>

</div>
<%= will_paginate @articles, render: WillPaginate::ActionView::BootstrapLinkRenderer %>

app/views/articles/new.html.erb
<h1>New Article</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', articles_path, :class => 'btn btn-primary' %>

app/views/articles/search.html.erb
<%= form_tag articles_path, :method => 'get' do %>
     <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag "Search", :name => nil %>
     </p>
 <% end %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
 
<h2>Comments</h2>
<%= render @article.comments %>
 
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
 
<%= link_to 'Edit', edit_article_path(@article), :class => 'btn btn-primary' %> |
<%= link_to 'Back', articles_path, :class => 'btn btn-primary' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.commenter %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>
 
<p>
  <%= link_to 'Destroy Comment', [comment.article, comment],
       method: :delete,
       data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_with(model: [ @article, @article.comments.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'%>
  </head>
<div class=”container"> 
  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
<p class="navbar-text float-right">
<% if admin_signed_in? %>
  Logged in as <strong><%= current_admin.email %></strong>.

  <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' , :class => 'btn btn-info'%> |
  <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link' , :class => 'btn btn-danger' %>
<% else %>
  <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link' , :class => 'btn btn-primary'%> |
  <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  , :class => 'btn btn-success'%>
<% end %>
</p>
    
    <%= yield %>
  </body>
  </div>

</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :login %>
    <%= form.text_field :login %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Login</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.login %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<h5><%= link_to 'My Blog', 'articles', :class => "btn btn-success" %></h5><br><br>

<h3><div>This blog is a basic information provider page, which provides basic info related to ROR technologies and gems </div></h3>